base:
  config:
    nacos:
      hostname: 192.168.17.134
      port: 8848
  oauth2:
    grant_type: password
    client_id: client
    client_secret: secret

spring:
  application:
    name: oauth2-server
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    jdbc-url: jdbc:mysql://192.168.17.131:3306/zero-user?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}
  redis:
    host: 192.168.17.131
    password: 123456

dubbo:
  scan:
    base-packages: com.demo.zero.service.ouath2.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${base.config.nacos.hostname}
    port: ${base.config.nacos.port}

server:
  port: 9001

